### ISSUE TITLE
[BE] Tests: Reduce the amount of DBs' initializations

### ISSUE THREAD

**Issue by Corgam** [Corgam/SS23_ADSP_TCF#100]
Currently, for each of the test files, a new instance of MongoDB is created, thus hitting the performance and speed of the tests. More research has to be done on how to improve it, without the problem of test dependence. That is, when certain tests are run they modify the DB changing the results of other tests.

**Comment by Fr3574** [comment]
Closing, as reducing the DB inits would introduce the mentioned test dependencies.
