### ISSUE TITLE
[FE] Change Upload-Workflow

### ISSUE THREAD

**Issue by thdrbrkw** [Corgam/SS23_ADSP_TCF#113]
Following Emil's mocks, the dashboad tiles should be rearanged. When clicking on uploading, another dashboad view should be opened with the tiles displayed as in the mock.

- no file ->  routing to  `upload/no-file`
- other fileformat -> routing to `upload/file/<TYPE OF DATA>`
- dataset -> routing to `upload/dataset/<TYPE OF DATASET>`

Within the upload-component
- remove toggle button for (un-)referenced data
- either the data file can now be opened within the dialog or in the upload component. Regardless, only the upload of specified filetype is allowed.

Depending on the user action:
- no file -> display fields for unreferenced data
- other fileformat -> display fields for referenced data, 
- dataset -> Show only fields for description, tags.

Depending on the user action, data is saved the following way:
- no file -> use normal CRUD endpoint
- other fileformat -> CRUD endpoint and after `/<documentID>/attach`-endpoint
- dataset -> `/fromFile`-endpoint with description and tags as form-fields

Also the fields for the adress can be removed (address search will haben with #114 )

![main](https://github.com/Corgam/SS23_ADSP_TCF/assets/105156462/a1fe993b-a579-412b-bb44-641cbed12185)
![grafik](https://github.com/Corgam/SS23_ADSP_TCF/assets/105156462/fbe2e9a1-380c-4d47-9604-a49fde35279a)

**Comment by Corgam** [comment]
After talking with Theo and some BE changes, when creating a new raw type datafile, the field `dataSet` for the data object should be `NONE`, except when uploading the dataset files, then it should be `SIMRA` or `CERV2`.

**Comment by Corgam** [comment]
Done with #82
