### ISSUE TITLE
[FE] Map-Changes

### ISSUE THREAD

**Issue by thdrbrkw** [Corgam/SS23_ADSP_TCF#114]
- move address-search into Map
- disable coordinate search
- address delete current input
- Output: Coordinate, Search-Area
- Input: Adress, Coordinate, points
![grafik](https://github.com/Corgam/SS23_ADSP_TCF/assets/105156462/53f182cb-72ae-4a73-8056-db2750b20392)

**Comment by Corgam** [comment]
The map should also have an ability to show all datapoints from a set #17 .
