### ISSUE TITLE
[FE] Journey Component

### ISSUE THREAD

**Issue by thdrbrkw** [Corgam/SS23_ADSP_TCF#115]
This compont shoud serve as a wrapper, which includes the different components (map, filter, result).
Based on different filters, the component should query the data and pass it to the Trace-Result-Component (#116). 

Part of this Issue is also the implementation of the upper righthand filters. The filters by this component as well as those by the map are `DataFileAnyFilter`, which the choosen infrastructure (store/services/observables) needs to store. As soon as those filter changes, the filter have to be applied and the data reloaded. Filters can be set iteratively, e.g. multiple traces.

Also, the Trace-Result-Component (#116) will provide IDs of datapoints, not to be included  in the final trace. However, this datapoint-filter MUST NOT be included into the queries, because otherwise the user can't reselect the datapoint). The datapoint filter will become relevant when saving the data. However, the filter will be applied to the inputs of the map, where the selected/ visible points are displayed.

- Downloading the data: Of the data in the trace result, only the selected datapoints should be downloaded. The downloading will happen in the frontend. @Fr3574 provides a feature for that. Please make the button similar to Save and Continue.
- Saveing & Continue: For now, the backend calls can be omitted as long as BE has not build the feature (#118 ). Regardless, the Save-Dialog can be implemented as in the mocks but also with a `title` attribute.
- Header: Name of the trace and number of iterative step

![grafik](https://github.com/Corgam/SS23_ADSP_TCF/assets/105156462/5de04940-0c04-40d1-99ba-bdf3238fd454)
![grafik](https://github.com/Corgam/SS23_ADSP_TCF/assets/105156462/ca98ab05-b3f0-41a9-b4f7-83ce013b1a5c)

**Comment by Corgam** [comment]
Done #163
