### ISSUE TITLE
[FE] Journey-Results

### ISSUE THREAD

**Issue by thdrbrkw** [Corgam/SS23_ADSP_TCF#116]
The Journey-Component (#115) provides the results from the BE call to this component. 
- The data has to be grouped by the `dataset` attribute (TODO REF)
- Preferably, each dataset is collapsable.
- Each Dataset and each datapoint has to have a radiobutton for selection/deselction. As soon as on set/point is (de-)selected, this has to be propagated to the Journey-Component.
- Each datapoint can be inspected. @salbani is working at a component for this - please ask him for this feature.
- TODO: Downloading each datapoint?

![grafik](https://github.com/Corgam/SS23_ADSP_TCF/assets/105156462/3a1dbb67-fdf5-4a28-abcb-2805fd16aa1c)
![grafik](https://github.com/Corgam/SS23_ADSP_TCF/assets/105156462/e6411a0f-2d09-407c-8ed1-19401c200e99)
![grafik](https://github.com/Corgam/SS23_ADSP_TCF/assets/105156462/763729d8-4e95-4861-ad4f-b4e9d78fa84f)

**Comment by Corgam** [comment]
Done #163 .
