### ISSUE TITLE
[FE] Change header

### ISSUE THREAD

**Issue by thdrbrkw** [Corgam/SS23_ADSP_TCF#117]
Make the "log in as ..." and logout button smaller and offer a button to browse traces. 
The Button does not need a functionalitiy yet but should only be visible in the Journey-Component.

![grafik](https://github.com/Corgam/SS23_ADSP_TCF/assets/105156462/bbd2d1a3-2240-47a9-a7ff-afbdc52c48e1)

**Comment by Corgam** [comment]
The name of the trace should also be visible in the left-side corner.

**Comment by flori950** [comment]
If youare at the specific path ?

**Comment by thdrbrkw** [comment]
Currently paused due to changed requirements

**Comment by flori950** [comment]
Make changes If you know more.

**Comment by Corgam** [comment]
Duplicate of #126
