### ISSUE TITLE
[BE] Support searching for similar traces

### ISSUE THREAD

**Issue by Corgam** [Corgam/SS23_ADSP_TCF#124]
New end-point:
Input: trace ID
Function: filter all similar traces: 
- siblings from the same parent
- geo-location overlap of `>=80%` (required)
- `>=50%` tags the same
- `>=50%` datapoints the same
Output: list of similar traces

**Comment by Fr3574** [comment]
@Corgam how would someone define a geo-location overlap?

**Comment by Fr3574** [comment]
@Corgam same for tags, when would we say tags are the same? Do just one single tag has to be in both traces or is 100% overlap here only meant if all tags are the same?

**Comment by Corgam** [comment]
After a meeting with UDK, we have decided it is no longer necessary.
