### ISSUE TITLE
[FE] Optimize the New Journey page

### ISSUE THREAD

**Issue by Corgam** [Corgam/SS23_ADSP_TCF#189]
Currently, the New Journey Page is lagging when many datafiles are fetched.
I suggest: 
- Pagination for the results inside individual collections
- What happens when the map is passed an object without proper coords? Does it try to render it?
- Maybe some other map improvements.

**Comment by salbani** [comment]
@Corgam I don't know if there is an easy way to optimize for many datafiles. I suspect the list in the collection tab to be the least impactful. I suppose the points on the map are the most taxing followed by the gallery-view and then the result view. I assume it will be a longer and laborious task to achieve.

Do you have an easy way to import many data points und which conditions you tested it?

**Comment by Corgam** [comment]
@salbani In that case I would leave it and write a section about FE performance and how it could be possibly improved in the report, what do you think @thdrbrkw?

**Comment by Corgam** [comment]
Closed to being out of scope. We will write about it in the report.
