### ISSUE TITLE
[FE] Finishing touches to Journeys Pages

### ISSUE THREAD

**Issue by Corgam** [Corgam/SS23_ADSP_TCF#190]
- [x] New Journey: Save instead of Continue Journey with the old saving icon
- [x] Browse Journeys: hint after hovering for download and delete buttons
- [x] New Journey: More suiting default values for tags & description  
- [x] New Journey: Add labels for all fields 
- [x] New Journey: Details popup should include the whole object, not only the `content.data`.
- [x] Bug: When updating a datapoint (View datasets panel) the return arrow returns to the upload page and not the view datasets page (Simon)
- [x] New Journey: Saving pop-up styling + datafile details pop-up styling
- [x] Document FE: Journey service infrastructure

**Comment by salbani** [comment]
@Corgam what do you invision under "New Journey: Saving pop-up styling + datafile details pop-up styling"? I added a bit more padding and made the save popup a bit bigger. (_checkout https://github.com/Corgam/SS23_ADSP_TCF/tree/frontend/journey-finishing-touches_)

**Comment by salbani** [comment]
@Corgam do you want the infrastructure documented in the code via comments or in the wiki?

**Comment by Corgam** [comment]
Done via #200
