### ISSUE TITLE
Development: Move MongoDB to the Cloud

### ISSUE THREAD

**Issue by Corgam** [Corgam/SS23_ADSP_TCF#51]
Our database should be permanently moved to the GCP running ideally on some low-cost machine.

**Comment by Fr3574** [comment]
As discussed with @thdrbrkw, as we deploy with docker-compose, we don't need this story but rather some way of populating the local mongoDB with data. As through the docker-volume there is already support for persistence, spinning up a local mongoDB through docker compose should be enough for developing and testing.
